cargo-features = ["edition2024"]
[package]
name = "sol-program-counter"
version = "0.1.0"
edition = "2024"

[lib]
name = "sol_counter"
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.6"
borsh-derive = "1.5.6"
solana-program = "1.18.26"
bytemuck_derive = "=1.7.0"
